[2024-02-14 14:46:31,014: INFO: main: welcome to my log]
[2024-02-14 17:51:22,535: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-14 17:51:22,536: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 17:51:22,537: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 17:51:22,537: INFO: common: created directory at: artifacts]
[2024-02-14 17:51:22,537: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-14 17:51:22,537: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 17:52:01,445: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 17:52:05,646: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-14 19:01:37,951: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 19:01:37,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 19:01:37,954: INFO: common: created directory at: artifacts]
[2024-02-14 19:01:37,954: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-14 19:01:37,954: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 19:02:08,570: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 19:28:55,827: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 19:28:55,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 19:28:55,829: INFO: common: created directory at: artifacts]
[2024-02-14 19:28:55,829: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-14 19:29:46,666: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 19:29:46,668: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 19:29:46,668: INFO: common: created directory at: artifacts]
[2024-02-14 19:29:46,669: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-14 19:29:54,058: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-14 19:37:56,411: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-14 19:37:56,412: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 19:37:56,412: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 19:37:56,413: INFO: common: created directory at: artifacts]
[2024-02-14 19:37:56,413: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-14 19:37:56,413: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 19:38:30,300: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 19:38:35,280: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-14 19:38:35,280: INFO: main: *******************]
[2024-02-14 19:38:35,280: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-14 19:38:35,281: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 19:38:35,282: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 19:38:35,282: INFO: common: created directory at: artifacts]
[2024-02-14 19:38:35,282: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-14 19:38:36,049: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-14 19:38:36,242: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-14 20:01:23,251: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 20:01:23,253: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 20:01:23,253: INFO: common: created directory at: artifacts]
[2024-02-14 20:01:23,254: INFO: common: created directory at: artifacts/training]
[2024-02-14 20:02:41,903: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-14 20:02:41,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 20:02:41,905: INFO: common: created directory at: artifacts]
[2024-02-14 20:02:41,906: INFO: common: created directory at: artifacts/training]
[2024-02-16 13:51:01,069: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 13:51:01,071: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:51:01,073: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:51:01,073: INFO: common: created directory at: artifacts]
[2024-02-16 13:51:01,073: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 13:51:01,073: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 13:51:50,746: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 13:51:57,889: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 13:51:57,889: INFO: main: *******************]
[2024-02-16 13:51:57,889: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 13:51:57,891: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:51:57,892: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:51:57,892: INFO: common: created directory at: artifacts]
[2024-02-16 13:51:57,893: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 13:51:58,804: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 13:51:59,046: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 13:51:59,046: INFO: main: *******************]
[2024-02-16 13:51:59,046: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-16 13:51:59,049: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:51:59,051: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:51:59,051: INFO: common: created directory at: artifacts]
[2024-02-16 13:51:59,052: INFO: common: created directory at: artifacts/training]
[2024-02-16 13:51:59,342: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_trainer.main()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/components/model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-scan-image'
[2024-02-16 13:56:12,276: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 13:56:12,278: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:56:12,279: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:56:12,280: INFO: common: created directory at: artifacts]
[2024-02-16 13:56:12,280: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 13:56:12,280: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 13:56:50,301: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 13:56:57,022: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 13:56:57,022: INFO: main: *******************]
[2024-02-16 13:56:57,022: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 13:56:57,023: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:56:57,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:56:57,025: INFO: common: created directory at: artifacts]
[2024-02-16 13:56:57,025: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 13:56:57,902: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 13:56:58,109: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 13:56:58,109: INFO: main: *******************]
[2024-02-16 13:56:58,109: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-16 13:56:58,110: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 13:56:58,112: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 13:56:58,112: INFO: common: created directory at: artifacts]
[2024-02-16 13:56:58,112: INFO: common: created directory at: artifacts/training]
[2024-02-16 13:56:58,389: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-images']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_trainer.main()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/components/model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-images'
[2024-02-16 14:00:09,031: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 14:00:09,033: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 14:00:09,034: INFO: common: created directory at: artifacts]
[2024-02-16 14:00:09,035: INFO: common: created directory at: artifacts/training]
[2024-02-16 15:15:51,386: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 15:15:51,388: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:15:51,389: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:15:51,390: INFO: common: created directory at: artifacts]
[2024-02-16 15:15:51,390: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 15:15:51,390: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 15:16:29,250: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 15:16:35,570: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 15:16:35,570: INFO: main: *******************]
[2024-02-16 15:16:35,570: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 15:16:35,571: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:16:35,573: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:16:35,573: INFO: common: created directory at: artifacts]
[2024-02-16 15:16:35,573: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 15:16:36,982: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 15:16:37,161: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 15:16:37,161: INFO: main: *******************]
[2024-02-16 15:16:37,161: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-16 15:16:37,163: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:16:37,164: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:16:37,164: INFO: common: created directory at: artifacts]
[2024-02-16 15:16:37,164: INFO: common: created directory at: artifacts/training]
[2024-02-16 15:16:37,464: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-images']
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    model_trainer.main()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/pipeline/stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/components/model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/preprocessing/image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/kidney-ct-images'
[2024-02-16 15:24:30,787: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 15:24:30,788: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:24:30,790: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:24:30,790: INFO: common: created directory at: artifacts]
[2024-02-16 15:24:30,790: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 15:24:30,790: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 15:25:21,338: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 15:25:28,058: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 15:25:28,058: INFO: main: *******************]
[2024-02-16 15:25:28,058: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 15:25:28,059: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:25:28,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:25:28,061: INFO: common: created directory at: artifacts]
[2024-02-16 15:25:28,061: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 15:25:29,274: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 15:25:29,527: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 15:25:29,527: INFO: main: *******************]
[2024-02-16 15:25:29,527: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-16 15:25:29,529: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 15:25:29,530: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 15:25:29,530: INFO: common: created directory at: artifacts]
[2024-02-16 15:25:29,530: INFO: common: created directory at: artifacts/training]
[2024-02-16 16:09:50,140: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-16 17:11:34,958: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 17:11:34,960: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 17:11:34,961: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 17:11:34,961: INFO: common: created directory at: artifacts]
[2024-02-16 17:11:34,961: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 17:11:34,961: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 17:12:24,081: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 17:12:30,459: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 17:12:30,459: INFO: main: *******************]
[2024-02-16 17:12:30,459: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 17:12:30,460: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 17:12:30,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 17:12:30,462: INFO: common: created directory at: artifacts]
[2024-02-16 17:12:30,462: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 17:12:31,218: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 17:12:31,390: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 17:12:31,390: INFO: main: *******************]
[2024-02-16 17:12:31,390: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-16 17:12:31,391: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 17:12:31,392: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 17:12:31,393: INFO: common: created directory at: artifacts]
[2024-02-16 17:12:31,394: INFO: common: created directory at: artifacts/training]
[2024-02-16 17:54:08,539: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-16 17:54:08,547: INFO: main: *******************]
[2024-02-16 17:54:08,547: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-16 17:54:08,549: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 17:54:08,550: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 17:54:08,550: INFO: common: created directory at: artifacts]
[2024-02-16 17:58:08,204: INFO: common: json file saved at: scores.json]
[2024-02-16 17:58:08,204: INFO: common: json file saved at: scores.json]
[2024-02-16 17:58:08,205: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-16 18:42:23,870: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-16 18:42:23,873: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 18:42:23,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 18:42:23,875: INFO: common: created directory at: artifacts]
[2024-02-16 18:42:23,875: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-16 18:42:23,875: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 18:42:55,508: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1AL7Q6PKZKfVEMiI1eVGe6kJjkNhZVtDk/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-16 18:43:01,894: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-16 18:43:14,838: INFO: stage_02_prepare_base_model: *******************]
[2024-02-16 18:43:14,838: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-16 18:43:14,840: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 18:43:14,841: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 18:43:14,841: INFO: common: created directory at: artifacts]
[2024-02-16 18:43:14,841: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-16 18:43:15,933: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-16 18:43:16,116: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-16 18:43:20,338: INFO: stage_03_model_training: *******************]
[2024-02-16 18:43:20,338: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-02-16 18:43:20,340: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 18:43:20,341: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 18:43:20,341: INFO: common: created directory at: artifacts]
[2024-02-16 18:43:20,341: INFO: common: created directory at: artifacts/training]
[2024-02-16 19:54:27,043: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-16 19:54:33,392: INFO: stage_04_model_evaluation: *******************]
[2024-02-16 19:54:33,393: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-16 19:54:33,395: INFO: common: yaml file: config/config.yaml loaded successfully]
[2024-02-16 19:54:33,396: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-16 19:54:33,396: INFO: common: created directory at: artifacts]
[2024-02-16 19:59:03,343: INFO: common: json file saved at: scores.json]
[2024-02-16 19:59:03,343: INFO: common: json file saved at: scores.json]
[2024-02-16 19:59:03,343: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-17 17:39:25,999: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.11:8080]
[2024-02-17 17:39:25,999: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-17 17:39:43,861: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 17:39:43] "GET / HTTP/1.1" 200 -]
[2024-02-17 17:40:09,255: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-17 17:40:09,259: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 17:40:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-17 17:53:28,959: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 17:53:28] "GET / HTTP/1.1" 200 -]
[2024-02-17 17:57:24,253: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/home/vishal/Documents/Kidney_disease_classification/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vishal/anaconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2024-02-17 17:57:24,254: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 17:57:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-02-17 18:00:38,869: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.11:8080]
[2024-02-17 18:00:38,869: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-17 18:00:48,739: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 18:00:48] "GET / HTTP/1.1" 200 -]
[2024-02-17 18:00:56,794: INFO: _internal: 127.0.0.1 - - [17/Feb/2024 18:00:56] "POST /predict HTTP/1.1" 200 -]
